services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/sample_django_app
      - DJANGO_SECRET_KEY=your-secret-key-here
    depends_on:
      - db
      - memcache
    volumes:
      - .:/app
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8000/health/')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=sample_django_app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  memcache:
    image: memcached:1.6-alpine
    command: memcached -m 128

volumes:
  postgres_data: 